/// Author: Nicos Kasenides

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1t-pXEvcAoh3eTCmj70jePKc87N03Tj8',
    appId: '1:634996880368:web:5be615ab6448c2d3a22335',
    messagingSenderId: '634996880368',
    projectId: 'sign-language-learning-a-c2ae0',
    authDomain: 'sign-language-learning-a-c2ae0.firebaseapp.com',
    databaseURL: 'https://sign-language-learning-a-c2ae0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sign-language-learning-a-c2ae0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERdqMB5FTFsDce7c3smnJM-aF_l0GrVI',
    appId: '1:634996880368:android:4310d84f5d20dd83a22335',
    messagingSenderId: '634996880368',
    projectId: 'sign-language-learning-a-c2ae0',
    databaseURL: 'https://sign-language-learning-a-c2ae0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sign-language-learning-a-c2ae0.firebasestorage.app',
  );

}